version: '3'
services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
    volumes:
      - ./data/db:/data/db
    tty: true
    expose:
      - ${MONGO_DB_PORT}
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  # api:
  #   build:
  #     context: .
  #   ports:
  #     - ${SEVER_PORT}:${SEVER_PORT}
  #   volumes:
  #     - .:/usr/src/app
  #   tty: true
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
  #   expose:
  #     - ${SEVER_PORT}
