#!/usr/bin/env bash

COMPOSE="docker-compose -f docker-compose.yml"
APP="api"
if [[ $# -gt 0 ]]; then
    if [[ "$1" == "start" ]]; then
        ${COMPOSE} up -d
    elif [[ "$1" == "start:dev" ]]; then
        $COMPOSE down && ${COMPOSE} up -d && $COMPOSE exec $APP npm run start:dev    
    elif [[ "$1" == "stop" ]]; then
        ${COMPOSE} down
    elif [[ "$1" == "status" ]]; then
        ${COMPOSE} ps
    elif [[ "$1" == "restart" ]]; then
        ${COMPOSE} down && ${COMPOSE} up -d
    elif [[ "$1" == "destroy" ]]; then
        ${COMPOSE} down --volumes --remove-orphans --rmi local
    elif [ "$1" == "install:ci" ]; then
        ${COMPOSE} exec -T $APP npm ci    
    elif [ "$1" == "run" ]; then
        shift 1
        ${COMPOSE} exec -T $APP npm run "$@"
    else
        ${COMPOSE} "$@"
    fi
else
    ${COMPOSE}
fi
